<a href="https://colab.research.google.com/github/MOhitambika7/Python_Basics/blob/main/Pandas02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

mySeries = ["Alex", "Sofiya", "Daniel", "Andrew"]
myIndex = ["A", "B", "C", "D"]
myDetails = pd.Series(mySeries, myIndex)
myDetails

A      Alex
B    Sofiya
C    Daniel
D    Andrew
dtype: object

In [ ]:
#To print the specific values from above code.
myDetails["B"]

'Sofiya'

In [ ]:
cars = {"Car1": "Mercedes", "Car2": "Morris-Garrage", "Car3": "Hyundai", "Car4": "Pugggeot"}
MyCars = pd.Series(cars)
MyCars
print(f"My car in the index number 2 i.e (car3) is:- {MyCars.loc['Car3 ']}" )

My car in the index number 2 i.e (car3) is:- Hyundai

Data frames in pandas

In [ ]:
import pandas as pd
import numpy as np
from numpy.random import randn
myData = randn(4,3) # 4 rows and 3 columns.
myRows = ("A", "B", "C", "D")
myColumns = ("Col1", "Col2", "Col3")

#creating the dataframe.
myDataframe = pd.DataFrame(myData, myRows, myColumns)
print(myDataframe)

       Col1      Col2      Col3
A -0.311877  1.282725 -0.159420
B -0.091424  0.904013  0.821546
C -0.405969 -0.596271 -0.423009
D -1.174331 -0.980653 -0.768517

Importing CSV files.

In [ ]:
myDataframe2 = pd.read_csv("/content/car data.csv")
print(myDataframe2)

    Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type  \
0       ritz  2014           3.35           5.59       27000    Petrol
1        sx4  2013           4.75           9.54       43000    Diesel
2       ciaz  2017           7.25           9.85        6900    Petrol
3    wagon r  2011           2.85           4.15        5200    Petrol
4      swift  2014           4.60           6.87       42450    Diesel
..       ...   ...            ...            ...         ...       ...
296     city  2016           9.50          11.60       33988    Diesel
297     brio  2015           4.00           5.90       60000    Petrol
298     city  2009           3.35          11.00       87934    Petrol
299     city  2017          11.50          12.50        9000    Diesel
300     brio  2016           5.30           5.90        5464    Petrol

    Seller_Type Transmission  Owner
0        Dealer       Manual      0
1        Dealer       Manual      0
2        Dealer       Manual      0
3        Dealer       Manual      0
4        Dealer       Manual      0
..          ...          ...    ...
296      Dealer       Manual      0
297      Dealer       Manual      0
298      Dealer       Manual      0
299      Dealer       Manual      0
300      Dealer       Manual      0

[301 rows x 9 columns]

In [ ]:
#.loc stands for location. i.e accessing each rows using location method with index input.
myDataframe2.loc[0]

Car_Name           ritz
Year               2014
Selling_Price      3.35
Present_Price      5.59
Kms_Driven        27000
Fuel_Type        Petrol
Seller_Type      Dealer
Transmission     Manual
Owner                 0
Name: 0, dtype: object

In [ ]:
# To pull out the multiple rows we use as below method.
myDataframe2.loc[[0,5]]

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
5,vitara brezza,2018,9.25,9.83,2071,Diesel,Dealer,Manual,0

# Grabing 5 rows from the dataset

In [4]:
import pandas as pd
import numpy as np
myDf1 = pd.read_csv("/content/archive (2).zip")
myDf1

,Unnamed: 0,Trek,Cost,Time,Trip Grade,Max Altitude,Accomodation,Best Travel Time,Contact or Book your Trip
0,0,Everest Base Camp Trek,"\n$1,420 USD",16 Days,Moderate,5545 m,Hotel/Guesthouse,March - May & Sept - Dec,https://www.nepalhikingteam.com
1,1,Everest Base Camp Short Trek,"\n$1,295 USD",14 Days,Moderate,5545 m,Hotel/Guesthouse,March - May & Sept - Dec,https://www.nepalhikingteam.com
2,2,Everest Base Camp Heli Shuttle Trek,\n$2000 USD,12 Days,Moderate,5545 m,Hotel/Guesthouse,March - May & Sept - Dec,https://www.nepalhikingteam.com
3,3,Everest Base Camp Heli Trek,"\n$3,300 USD",11 Days,Moderate,5545 m,Hotel/Guesthouse,March - May & Sept - Dec,https://www.nepalhikingteam.com
4,4,Everest Base Camp Trek for Seniors,"\n$1,800 USD",20 Days,Moderate,5545 m,Hotel/Guesthouse,March - May & Sept - Dec,https://www.nepalhikingteam.com
...,...,...,...,...,...,...,...,...,...
378,378,Ghorepani Poon Hill Trek,$450 USD,10 Days,Easy,"3,210m",Hotel/Guesthouse,Jan - May & Sept - Dec,https://www.adventurehimalayacircuit.com
379,379,Upper Mustang Trek,$2100 USD,17 Days,Moderate-Hard,4200m,Hotel/Guesthouse,Jan - May & Sept - Dec,https://www.adventurehimalayacircuit.com
380,380,Mardi Himal Trek,$590 USD,9 Days,Easy-Moderate,"4,500m",Hotel/Guesthouse,Jan - May & Sept - Dec,https://www.adventurehimalayacircuit.com
381,381,Langtang Valley Trekking,$690 USD,11 Days,Moderate,"4,773m",Hotel/Guesthouse,Jan - May & Sept - Dec,https://www.adventurehimalayacircuit.com
382,382,Manaslu Circuit Trek,$1190 USD,17 Days,Moderate-Hard,"5,220m",Hotel/Guesthouse,Jan - May & Sept - Dec,https://www.adventurehimalayacircuit.com

In [5]:
myDf1.loc[[0,5]]

,Unnamed: 0,Trek,Cost,Time,Trip Grade,Max Altitude,Accomodation,Best Travel Time,Contact or Book your Trip
0,0,Everest Base Camp Trek,"\n$1,420 USD",16 Days,Moderate,5545 m,Hotel/Guesthouse,March - May & Sept - Dec,https://www.nepalhikingteam.com
5,5,Everest Chola Pass Trek,"\n$1,720 USD",19 Days,Strenuous,5545 m,Hotel/Guesthouse,March - May & Sept - Dec,https://www.nepalhikingteam.com

In [6]:
# Grabing the first five rows.
myDf1.head()

,Unnamed: 0,Trek,Cost,Time,Trip Grade,Max Altitude,Accomodation,Best Travel Time,Contact or Book your Trip
0,0,Everest Base Camp Trek,"\n$1,420 USD",16 Days,Moderate,5545 m,Hotel/Guesthouse,March - May & Sept - Dec,https://www.nepalhikingteam.com
1,1,Everest Base Camp Short Trek,"\n$1,295 USD",14 Days,Moderate,5545 m,Hotel/Guesthouse,March - May & Sept - Dec,https://www.nepalhikingteam.com
2,2,Everest Base Camp Heli Shuttle Trek,\n$2000 USD,12 Days,Moderate,5545 m,Hotel/Guesthouse,March - May & Sept - Dec,https://www.nepalhikingteam.com
3,3,Everest Base Camp Heli Trek,"\n$3,300 USD",11 Days,Moderate,5545 m,Hotel/Guesthouse,March - May & Sept - Dec,https://www.nepalhikingteam.com
4,4,Everest Base Camp Trek for Seniors,"\n$1,800 USD",20 Days,Moderate,5545 m,Hotel/Guesthouse,March - May & Sept - Dec,https://www.nepalhikingteam.com

In [7]:
# Grabing the custom rows.
myDf1.head(10)

,Unnamed: 0,Trek,Cost,Time,Trip Grade,Max Altitude,Accomodation,Best Travel Time,Contact or Book your Trip
0,0,Everest Base Camp Trek,"\n$1,420 USD",16 Days,Moderate,5545 m,Hotel/Guesthouse,March - May & Sept - Dec,https://www.nepalhikingteam.com
1,1,Everest Base Camp Short Trek,"\n$1,295 USD",14 Days,Moderate,5545 m,Hotel/Guesthouse,March - May & Sept - Dec,https://www.nepalhikingteam.com
2,2,Everest Base Camp Heli Shuttle Trek,\n$2000 USD,12 Days,Moderate,5545 m,Hotel/Guesthouse,March - May & Sept - Dec,https://www.nepalhikingteam.com
3,3,Everest Base Camp Heli Trek,"\n$3,300 USD",11 Days,Moderate,5545 m,Hotel/Guesthouse,March - May & Sept - Dec,https://www.nepalhikingteam.com
4,4,Everest Base Camp Trek for Seniors,"\n$1,800 USD",20 Days,Moderate,5545 m,Hotel/Guesthouse,March - May & Sept - Dec,https://www.nepalhikingteam.com
5,5,Everest Chola Pass Trek,"\n$1,720 USD",19 Days,Strenuous,5545 m,Hotel/Guesthouse,March - May & Sept - Dec,https://www.nepalhikingteam.com
6,6,Gokyo Lake Renjo La Pass Trek,"\n$1,450 USD",16 Days,Moderate,5360 m,Hotel/Guesthouse,March - May & Sept - Dec.,https://www.nepalhikingteam.com
7,7,Everest High Passes Trek,"\n$1,950 USD",22 Days,Strenuous,5545 m,Hotel/Guesthouse,April - May & Sept - Nov,https://www.nepalhikingteam.com
8,8,Short Everest Trek,\n$1060 USD,7 Days,Easy To Moderate,3900 m,Hotel/Guesthouse,March - May & Sept - Dec.,https://www.nepalhikingteam.com
9,9,Everest Panorama Trek,\n$1150 USD,10 Days,Easy To Moderate,3860 m,Hotel/Guesthouse,Jan - May & Sept - Dec,https://www.nepalhikingteam.com

In [8]:
# Grabing last five rows.
myDf1.tail()

,Unnamed: 0,Trek,Cost,Time,Trip Grade,Max Altitude,Accomodation,Best Travel Time,Contact or Book your Trip
378,378,Ghorepani Poon Hill Trek,$450 USD,10 Days,Easy,"3,210m",Hotel/Guesthouse,Jan - May & Sept - Dec,https://www.adventurehimalayacircuit.com
379,379,Upper Mustang Trek,$2100 USD,17 Days,Moderate-Hard,4200m,Hotel/Guesthouse,Jan - May & Sept - Dec,https://www.adventurehimalayacircuit.com
380,380,Mardi Himal Trek,$590 USD,9 Days,Easy-Moderate,"4,500m",Hotel/Guesthouse,Jan - May & Sept - Dec,https://www.adventurehimalayacircuit.com
381,381,Langtang Valley Trekking,$690 USD,11 Days,Moderate,"4,773m",Hotel/Guesthouse,Jan - May & Sept - Dec,https://www.adventurehimalayacircuit.com
382,382,Manaslu Circuit Trek,$1190 USD,17 Days,Moderate-Hard,"5,220m",Hotel/Guesthouse,Jan - May & Sept - Dec,https://www.adventurehimalayacircuit.com

In [9]:
# Grabing certain number of custom rows from last.
myDf1.tail(10)

,Unnamed: 0,Trek,Cost,Time,Trip Grade,Max Altitude,Accomodation,Best Travel Time,Contact or Book your Trip
373,373,Everest Base Camp Trek via Gokyo Lake,$1530 USD,19 Days,Moderate-Hard,"5,545m",Hotel/Guesthouse,Jan - May & Sept - Dec,https://www.adventurehimalayacircuit.com
374,374,Gokyo Lake Trek,$1190 USD,13 Days,Moderate,"5,357m",Hotel/Guesthouse,Jan - May & Sept - Dec,https://www.adventurehimalayacircuit.com
375,375,Everest Base Camp Heli Trek,$3600 USD,9 Days,Moderate,"5,545m",Hotel/Guesthouse,Jan - May & Sept - Dec,https://www.adventurehimalayacircuit.com
376,376,Annapurna Circuit Trek,$1100 USD,19 Days,Moderate-Hard,"5,416m",Hotel/Guesthouse,Jan - May & Sept - Dec,https://www.adventurehimalayacircuit.com
377,377,Annapurna Base Camp Trek,$1090 USD,16 Days,Moderate,"4,130m",Hotel/Guesthouse,Jan - May & Sept - Dec,https://www.adventurehimalayacircuit.com
378,378,Ghorepani Poon Hill Trek,$450 USD,10 Days,Easy,"3,210m",Hotel/Guesthouse,Jan - May & Sept - Dec,https://www.adventurehimalayacircuit.com
379,379,Upper Mustang Trek,$2100 USD,17 Days,Moderate-Hard,4200m,Hotel/Guesthouse,Jan - May & Sept - Dec,https://www.adventurehimalayacircuit.com
380,380,Mardi Himal Trek,$590 USD,9 Days,Easy-Moderate,"4,500m",Hotel/Guesthouse,Jan - May & Sept - Dec,https://www.adventurehimalayacircuit.com
381,381,Langtang Valley Trekking,$690 USD,11 Days,Moderate,"4,773m",Hotel/Guesthouse,Jan - May & Sept - Dec,https://www.adventurehimalayacircuit.com
382,382,Manaslu Circuit Trek,$1190 USD,17 Days,Moderate-Hard,"5,220m",Hotel/Guesthouse,Jan - May & Sept - Dec,https://www.adventurehimalayacircuit.com

In [12]:
# Get information about our dataframe.
myDf1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 383 entries, 0 to 382
Data columns (total 9 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Unnamed: 0                 383 non-null    int64
 1   Trek                       383 non-null    object
 2   Cost                       383 non-null    object
 3   Time                       383 non-null    object
 4   Trip Grade                 383 non-null    object
 5   Max Altitude               383 non-null    object
 6   Accomodation               383 non-null    object
 7   Best Travel Time           383 non-null    object
 8   Contact or Book your Trip  383 non-null    object
dtypes: int64(1), object(8)
memory usage: 27.1+ KB

In [14]:
# Get the shape of rows and columns.
myDf1.shape

(383, 9)

In [15]:
# Get the number if dimension.
myDf1.ndim # Tells about the dimension of the table since it uses 2 dimension so it will return 2-D as output

2

In [ ]:
# Get the column data type.